name: Dev PR Review Bot
on:
  pull_request:

jobs:
  pr-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Run PR Review Bot
        uses: Devanshu1609/PR-Review-Bot@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config: .prbot.yml
