name: Dev PR Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr-review:
    runs-on: ubuntu-latest

    steps:
      - name: Run PR Review Bot
        uses: Devanshu1609/PR-Review-Bot@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
